
version : '3'
services:
  mysqldbserver:
    container_name: mysqldbserver
    build:
      context: .
      dockerfile: mysqldb-dockerfile
    environment:
    - "MYSQL_ROOT_PASSWORD=root"
    - "MYSQL_PASSWORD=root"
    - "MYSQL_DATABASE=dockertest"
    - "MYSQL_ROOT_HOST=%"
#    - "MYSQL_USER=root"
    ports:
    - "3306:3306"
    networks:
    - net-spring-db
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
  springappserver:
    container_name: springappserver
    build:
      context: .
      args:
        JAR_FILE: target/dockerfiledemo-0.0.1-SNAPSHOT.jar
      dockerfile: springapp-dockerfile
    ports:
    - "8080:8080"
    networks:
    - net-spring-db
#    volumes:
#    - /vol/development
    depends_on:
    - mysqldbserver
#    links:
#    - mysqldbserver

networks:
  net-spring-db:
    driver: bridge